apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "8"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"poi"},"name":"poi","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"poi"}},"template":{"metadata":{"labels":{"app":"poi"}},"spec":{"containers":[{"env":[{"name":"SQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"sqlcredential"}}},{"name":"SQL_USER","value":"sqladminpYf5956"},{"name":"SQL_SERVER","value":"sqlserverpyf5956.database.windows.net"}],"image":"registrypyf5956.azurecr.io/tripinsights/poi:1.0","name":"poi","ports":[{"containerPort":80}]}]}}}}
    generation: 8
    labels:
      app: poi
    name: poi
    namespace: api
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: poi
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: poi
      spec:
        containers:
        - env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aks-secret # name of our kubernetes secret
                key: sqlcredential # key specified in kubernetes secret
          - name: SQL_USER
            value: sqladminpYf5956
          - name: SQL_SERVER
            value: sqlserverpyf5956.database.windows.net
          image: registrypyf5956.azurecr.io/tripinsights/poi:1.0
          imagePullPolicy: IfNotPresent
          name: poi
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: secrets-store01-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "azure-kvname-user-msi"
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-04-20T09:22:00Z"
      lastUpdateTime: "2022-04-20T09:22:00Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-04-20T08:44:42Z"
      lastUpdateTime: "2022-04-20T13:17:20Z"
      message: ReplicaSet "poi-7d48c8db85" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 8
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "5"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"trips"},"name":"trips","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"trips"}},"template":{"metadata":{"labels":{"app":"trips"}},"spec":{"containers":[{"env":[{"name":"SQL_PASSWORD","value":"Password123!"},{"name":"SQL_USER","value":"sqladminpYf5956"},{"name":"SQL_SERVER","value":"sqlserverpyf5956.database.windows.net"},{"name":"SQL_DBNAME","value":"mydrivingDB"},{"name":"OPENAPI_DOCS_URI","value":"http://trips:80"}],"image":"registrypyf5956.azurecr.io/tripinsights/trips:1.0","name":"trips","ports":[{"containerPort":80}]}]}}}}
    generation: 5
    labels:
      app: trips
    name: trips
    namespace: api
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: trips
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: trips
      spec:
        containers:
        - env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aks-secret # name of our kubernetes secret
                key: sqlcredential # key specified in kubernetes secret
          - name: SQL_USER
            value: sqladminpYf5956
          - name: SQL_SERVER
            value: sqlserverpyf5956.database.windows.net
          - name: SQL_DBNAME
            value: mydrivingDB
          - name: OPENAPI_DOCS_URI
            value: http://trips:80
          image: registrypyf5956.azurecr.io/tripinsights/trips:1.0
          imagePullPolicy: IfNotPresent
          name: trips
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-04-20T10:31:58Z"
      lastUpdateTime: "2022-04-20T10:31:58Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-04-20T10:31:54Z"
      lastUpdateTime: "2022-04-20T11:46:09Z"
      message: ReplicaSet "trips-945b5b4f8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 5
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"tripviewer"},"name":"tripviewer","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"tripviewer"}},"template":{"metadata":{"labels":{"app":"tripviewer"}},"spec":{"containers":[{"env":[{"name":"TRIPS_API_ENDPOINT","value":"http://trips:80"},{"name":"USERPROFILE_API_ENDPOINT","value":"http://userprofile:80/api/user"}],"image":"registrypyf5956.azurecr.io/tripinsights/tripviewer:1.0","name":"tripviewer","ports":[{"containerPort":80}]}]}}}}
    generation: 1
    labels:
      app: tripviewer
    name: tripviewer
    namespace: web
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: tripviewer
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: tripviewer
      spec:
        containers:
        - env:
          - name: TRIPS_API_ENDPOINT
            value: http://trips.api:80
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile.api:80/api/user
          image: registrypyf5956.azurecr.io/tripinsights/tripviewer:1.0
          imagePullPolicy: IfNotPresent
          name: tripviewer
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-04-20T13:29:35Z"
      lastUpdateTime: "2022-04-20T13:29:35Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-04-20T13:29:33Z"
      lastUpdateTime: "2022-04-20T13:29:35Z"
      message: ReplicaSet "tripviewer-5bd7d7cf74" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"user-java"},"name":"user-java","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"user-java"}},"template":{"metadata":{"labels":{"app":"user-java"}},"spec":{"containers":[{"env":[{"name":"SQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"sqlcredential"}}},{"name":"SQL_USER","value":"sqladminpYf5956"},{"name":"SQL_SERVER","value":"sqlserverpyf5956.database.windows.net"},{"name":"SQL_DBNAME","value":"mydrivingDB"}],"image":"registrypyf5956.azurecr.io/tripinsights/user-java:1.0","name":"user-java","ports":[{"containerPort":80}]}]}}}}
    generation: 4
    labels:
      app: user-java
    name: user-java
    namespace: api
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: user-java
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: user-java
      spec:
        containers:
        - env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aks-secret # name of our kubernetes secret
                key: sqlcredential # key specified in kubernetes secret
          - name: SQL_USER
            value: sqladminpYf5956
          - name: SQL_SERVER
            value: sqlserverpyf5956.database.windows.net
          - name: SQL_DBNAME
            value: mydrivingDB
          image: registrypyf5956.azurecr.io/tripinsights/user-java:1.0
          imagePullPolicy: IfNotPresent
          name: user-java
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-04-20T10:16:27Z"
      lastUpdateTime: "2022-04-20T10:16:27Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-04-20T10:16:19Z"
      lastUpdateTime: "2022-04-20T13:14:38Z"
      message: ReplicaSet "user-java-6775965457" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 4
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"userprofile"},"name":"userprofile","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"userprofile"}},"template":{"metadata":{"labels":{"app":"userprofile"}},"spec":{"containers":[{"env":[{"name":"SQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"sqlcredential"}}},{"name":"SQL_USER","value":"sqladminpYf5956"},{"name":"SQL_SERVER","value":"sqlserverpyf5956.database.windows.net"},{"name":"SQL_DBNAME","value":"mydrivingDB"}],"image":"registrypyf5956.azurecr.io/tripinsights/userprofile:1.0","name":"userprofile","ports":[{"containerPort":80}]}],"hostname":"userprofile"}}}}
    generation: 4
    labels:
      app: userprofile
    name: userprofile
    namespace: api
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: userprofile
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: userprofile
      spec:
        containers:
        - env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aks-secret # name of our kubernetes secret
                key: sqlcredential # key specified in kubernetes secret
          - name: SQL_USER
            value: sqladminpYf5956
          - name: SQL_SERVER
            value: sqlserverpyf5956.database.windows.net
          - name: SQL_DBNAME
            value: mydrivingDB
          image: registrypyf5956.azurecr.io/tripinsights/userprofile:1.0
          imagePullPolicy: IfNotPresent
          name: userprofile
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        hostname: userprofile
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-04-20T10:18:53Z"
      lastUpdateTime: "2022-04-20T10:18:53Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-04-20T10:18:44Z"
      lastUpdateTime: "2022-04-20T13:18:05Z"
      message: ReplicaSet "userprofile-7769bd778f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 4
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
