apiVersion: v1
kind: Namespace
metadata:
   name: web
---
apiVersion: v1
kind: Namespace
metadata:
   name: api
---
apiVersion: v1
kind: Secret
metadata:
  name: sqlcredential
  namespace: api
type: Opaque
data:
  password: UGFzc3dvcmQxMjMh