apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: trips
    namespace: api
  spec:
    ports:
    - port: 80
    selector:
      app: trips
- apiVersion: v1
  kind: Service
  metadata:
    name: tripviewer
    namespace: web
  spec:
    ports:
    - port: 80
    selector:
      app: tripviewer
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    name: user-java
    namespace: api
  spec:
    ports:
    - port: 80
    selector:
      app: user-java
- apiVersion: v1
  kind: Service
  metadata:
    name: userprofile
    namespace: api
  spec:
    ports:
    - port: 80
    selector:
      app: userprofile
- apiVersion: v1
  kind: Service
  metadata:
    name: poi
    namespace: api
  spec:
    ports:
    - port: 80
    selector:
      app: poi
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

